export enum ErrorType {
  // OTP-related
  INVALID_OTP = 'INVALID_OTP',
  EXPIRED_OTP = 'EXPIRED_OTP',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Auth & Session
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED_ROLE = 'UNAUTHORIZED_ROLE',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
  INVALID_FORMAT = 'INVALID_FORMAT',
  FST_ERR_VALIDATION = 'FST_ERR_VALIDATION',
  FST_ERR_NOT_FOUND = 'FST_ERR_NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',

  // User-related
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  MOBILE_ALREADY_REGISTERED = 'MOBILE_ALREADY_REGISTERED',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  USER_NOT_ACTIVE = 'USER_NOT_ACTIVE',

  // Resource & Database
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  DATABASE_ERROR = 'DATABASE_ERROR',
  CONFLICT = 'CONFLICT',

  // External & Network
  SMS_SERVICE_ERROR = 'SMS_SERVICE_ERROR',
  EMAIL_SERVICE_ERROR = 'EMAIL_SERVICE_ERROR',
  PAYMENT_SERVICE_ERROR = 'PAYMENT_SERVICE_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  THIRD_PARTY_ERROR = 'THIRD_PARTY_ERROR',
  TIMEOUT = 'TIMEOUT',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',

  // System/Internal
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  FEATURE_NOT_IMPLEMENTED = 'FEATURE_NOT_IMPLEMENTED',
}
